# Basic metadata configuration for your blog.
theme = "rtc"
title = "Old Books, New Attitudes"
author = "Melissa Reynolds and students at TCU"
copyright = "Copyright © 2025"
languageCode = "en-US"

# Generate robots.txt for SEO
enableRobotsTXT = false

# Set to "WARNING" so that broken links don't break the build process. Default is "ERROR".
refLinksErrorLevel = "WARNING"
